### ISSUE TITLE
Bug: dev server continuously restarts

### ISSUE THREAD

**Issue by johncade** [stefanonepa/vuejs-webpack-express#1]
Hi, to recreate the issue:
 install template via the vue cli as explained in the documentation. Then run `npm start`. 

What happens? 
The nodemon server continuously restarts, so nothing can get served.

Expected result:
The nodemon server loads and serves the service.

**Comment by stefanonepa** [comment]
Hi John,

It is an old template, but I think you put the issue in a wrong one. Because there no nodemon in this template... 

I recommend you to use something more up2date like https://github.com/icebob/vue-express-mongo-boilerplate.
